<?php
/**
 * @file
 * Code for the DGU Consultation feature.
 */

include_once 'dgu_consultation.features.inc';

/**
 *  Implements hook_theme().
 */
function dgu_consultation_theme($existing, $type, $theme, $path) {
  return array(
    'consultation_index' => array(
      'variables' => array('consultation_index' => NULL),
      'path' => $path . '/templates/',
      'template' => 'consultation-index',
    ),
  );
}

/**
 *  Implements hook_theme_registry_alter().
 */
function dgu_consultation_theme_registry_alter(&$theme_registry) {
  //$theme_registry['book_navigation']['_preprocess functions'] = array(
  //  0 => 'dgu_consultation_preprocess_book_navigation'
  //);
  error_log('here');
}

function dgu_consultation_preprocess_book_index(&$variables){
  $parent_book = node_load($variables['book_link']['bid']);
  $variables['parent_book_title'] = $parent_book->title;
  $book_link = $variables['book_link'];

  // Provide extra variables for themers. Not needed by default.
  $variables['book_id'] = $book_link['bid'];
  $variables['book_title'] = check_plain($parent_book->title);
  $variables['book_url'] = 'node/' . $book_link['bid'];
  $variables['current_depth'] = $book_link['depth'];
  $variables['tree'] = '';
  $tree = menu_tree_all_data(book_menu_name($book_link['bid']));
  //$top_item = array_shift($tree);
  $index = array();
  $outline = array();
  $top_item = array_shift($tree);
  _dgu_consultation_build_index($top_item, $index, $book_link['mlid'], $outline);
  $elements = menu_tree_output(array('tree' => $index));
  $elements['#theme'] = array('consultation_index');
  $variables['tree'] = drupal_render($elements);
  //theme('consultation_index', array('consultation_index' => $index));

}

function _dgu_consultation_get_link_nid($link){
  $parts = explode('/', $link['link_path']);
  return $parts[1];
}

function _dgu_consultation_build_index($data, &$index, $current_mlid, &$outline, $depth_limit = null){

  $link = $data['link'];
  //Optionally limit the depth
  if ($depth_limit && $link['depth'] > $depth_limit) {
    break;
  }
  $index['link'] = $link;
  $index['link']['section'] = implode('.', $outline);
  $outline[] = 1;
  $index['link']['paragraphs'] = dgu_consultation_build_paragraph($link, $outline);
  $index['below'] = array();
  foreach ($data['below'] as $id => $subsection) {
    $index['below'][$id] = array();
    _dgu_consultation_build_index($subsection, $index['below'][$id], $current_mlid, $outline, $depth_limit);
    $outline[count($outline)-1]++;
  }
  array_pop($outline);
}

/**
 *  Implements hook_drupal_goto_alter().
 */
function dgu_consultation_build_paragraph($link, &$outline){
  $book_page = node_load(_dgu_consultation_get_link_nid($link));
  $paras = array();
  foreach ( $book_page->field_paragraph[LANGUAGE_NONE] as $para) {
    $paras[] = array(
      'section' => implode('.', $outline),
      'title' => truncate_utf8(strip_tags($para['safe_value']), 30, TRUE, TRUE),
    );
    $outline[count($outline)-1]++;
  }
  return $paras;
}

function dgu_consultation_to_roman($n){
  $c='IVXLCDM';
  for($a=5,$b=$s='';$n;$b++,$a^=7)
    for($o=$n%$a,$n=$n/$a^0;$o--;$s=$c[$o>2?$b+$n-($n&=-2)+$o=1:$b].$s);
  return $s;
}
